### ISSUE TITLE
It's not importing cURL requests with "$" on it

### ISSUE THREAD

**Issue by iamvinny** [postmanlabs/curl-to-postman#1]
**Describe the bug**
I'm trying to import a cURL request copied from Burp Suite, but it's adding the symbol "$" to the requests, which Postman doesn't seem to accept.

**To Reproduce**
1. Go to **Postman**
2. Click on **Import**
3. Click on **Paste Raw Text**
4. [Paste the request copied from Burp Suite](https://pastebin.com/raw/N73kbscr)
5. Click on Import
6. See error below.

![Screen Shot 2019-07-01 at 5 02 05 PM](https://user-images.githubusercontent.com/29668752/60463307-fe8cb980-9c21-11e9-9b13-fe2738a445d5.png)

**Expected behavior**
It was expected to correctly import the Burp Suite request into Postman.

**App information:**
 - App Type [Burp Suite Community Edition v2.1]
 - Postman Version [Postman 7.2.2]
 - OS: [macOS High Sierra 10.13.6]

**Additional context**
I have noticed that if I remove the "$" symbols from the Burp requests it imports as expected to Postman, with no errors, it used to work before, I'm not sure if it was any update on Burp Suite or on Postman.

**Comment by Dhroov7** [comment]
Resolved in 7.7.0!
